INSERT INTO TB_ITENS (NOM_ITEM, PTS_ITEM, DAT_CRIA) VALUES ('Arma',4,NOW());
INSERT INTO TB_ITENS (NOM_ITEM, PTS_ITEM, DAT_CRIA) VALUES ('Munição',3,NOW());
INSERT INTO TB_ITENS (NOM_ITEM, PTS_ITEM, DAT_CRIA) VALUES ('Água',2,NOW());
INSERT INTO TB_ITENS (NOM_ITEM, PTS_ITEM, DAT_CRIA) VALUES ('Comida',1,NOW());

INSERT INTO TB_GALAXIAS (NOM_GALX, DAT_CRIA) VALUES ('Via Láctea',NOW());